# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: kaveiii
google_analytics: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: A brain dump of written articles & slides

description: A brain dump of written articles & slides
author:
  name: Emmanuel Apau
  email: etapau@gmail.com
  github: kave
  linkedin: emmanuel-apau
  bio: Lead Site Reliability Engineer
  twitter: technogrouch
  medium: https://medium.com/@etapau
  email_md5: da82d85ae4b0e070a0955811e7f9f6ac

rss_path: rss.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

# Plugins
plugins: ["jekyll-paginate"]
